spring.application.name=NutritionTracker

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/nutrition_tracker
# db credentials
spring.datasource.username=andresbejarano
spring.datasource.password=


# JPA / Hibernate Settings

# Hibernate inspects the entities, and updates the data structure if necessary, neve delete.
# Create -> to drop the db in restart, clean db at every start
# Create-drop -> create tables on start up and drops them when app shut down
# At start it creates the tables
spring.jpa.hibernate.ddl-auto=update

# Print every sql query it generates and execute in the terminal, false in production cause it degrades the performance and can expose information
spring.jpa.show-sql=true
# Format clean sql in terminal (identation, line breaks, etc)
spring.jpa.properties.hibernate.format_sql=true
# Translate all java/jpa quesries into sql sintax, or other sintax like MySQL, if required
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Don't Run schema.sql or any .sql on startup let hibernate handle this . "always" to restart (since i have drops in schema.sql)
spring.sql.init.mode=never
